### ISSUE TITLE
検索フォームの実装

### ISSUE THREAD

**Issue by ri-i-i-sa** [ri-i-i-sa/member-management-system-project#14]
spreadsheetのAPIを実装（メンバーテーブルに対するselect、入力した値を利用できるようにSQL文を組み立てる）
各種検索項目を固定でAPIを叩き、レスポンスのjsonをconsole.logに表示できるかを確認
レスポンスのjsonを整形し、テーブルに表示する。
検索フォームの各項目に埋め込んだ値を使用し、APIを叩く
検索結果0件の場合の考慮

**Comment by tomohitokanno** [comment]
@ri-i-i-sa 
上から進めて行ってください。
【疎通確認編】
~~- [x] searchMembersという名前でgsにfunctionを追加する。~~
~~- [x] searchMembersの中身をreadMembersのものと一旦同一にする（疎通確認のため）~~
~~- [x] searchMembersをview=members&id=1の場合に取得するようにgs側に分岐を書く~~
~~- [x] ブラウザのjsに、検索ボタン発火時のイベントを書く~~
~~- [x] 検索ボタン発火時のイベント内でparamsにクエリ、id=1を設定、APIを叩く。~~
~~- [ ] 疎通確認：叩いたresponseをlogに出す。（ここでlogに出てきたら疎通ができているという証拠）~~

~~【カスタムクエリ実装編その１】~~
~~- [ ] searchMembersの中身をSpreadsSheetsSQL似合わせて書き直す、その際filterにidを設定する。~~
~~- [ ] 疎通確認：叩いたresponseをlogに出す。（ここでlogに出てきたら疎通ができているという証拠）~~
~~- [ ] paramsにクエリを全部（id,nameKanji,nameYomi,tel,rank）みそらちゃんの値を設定する~~
~~- [ ] searchMembersのfilterにid,nameKanji,nameYomi,tel,rankを追加する。~~
~~- [ ] 疎通確認：叩いたresponseをlogに出す。（ここでlogに出てきたら疎通ができているという証拠）~~

~~【カスタムクエリ実装編その２】~~
~~- [ ] ブラウザのjs、検索ボタン発火時のイベント内で検索フォームに値が入力された場合のみ、paramsに値を設定するようにする。~~
~~- [ ] searchMembersの中で、クエリが設定されていない場合、filterの検索条件に設定しないようにする。~~
【会員のjsonから検索する】



【画面実装編】
- [x] テキストボックスの入力上限を定義（maxLengthなど）する。
- [x] テキストボックスの入力上限にあわせて実装。
- [x] 電話番号に11桁（08012345678）の入力した場合、テキストボックスからカーソルを外した際ハイフン付与（080-1234-5678）する。

**Comment by ri-i-i-sa** [comment]
@tomohitokanno 
疎通確認のボタン発火時のイベントの仕様についてなのですが、

・ボタンをクリックしたら、index.htmlの後ろにパラメータをつける
・index.htmlをリロード
・新たにデータ取得（このときにview=members&id=1だったら該当するデータを出すようにフィルタリング）

で認識あってますか…？

**Comment by tomohitokanno** [comment]
@ri-i-i-sa 
だいたい認識あっています。

> ・index.htmlをリロード

ここですが、画面をリロードせずにAPIだけ叩けると思うので、
実装上どうしてもリロードされてしまう場合は相談ください。

> 新たにデータ取得（このときにview=members&id=1だったら該当するデータを出すようにフィルタリング）

齟齬があるといけないので訂正すると、
view=members&id=1だった場合、会員テーブルを全件取得（readMemberと処理が同じなのでこれで良し）
です

**Comment by ri-i-i-sa** [comment]
@tomohitokanno 
フォームやラジオボタンからの値を取得し、jsonデータからフィルタリングして表示するところまでは実装しています。

認識の相違がないように念のため確認させて頂きたいのですが、最終的に「AND検索」が出来るように実装ということであってますでしょうか？？（打ち合わせの際に既出の議題でしたら申し訳ありません。）

**Comment by tomohitokanno** [comment]
@ri-i-i-sa 
> 最終的に「AND検索」が出来るように実装ということであってますでしょうか？？（打ち合わせの際に既出の議題でしたら申し訳ありません。）

はいそうです。
検索項目に入力された値が、
id が 1
名前が 美空結音
の場合は対象のデータあり

id が 1
名前が 小林良文
の場合は対象のデータなし

となります。

**Comment by ri-i-i-sa** [comment]
@tomohitokanno 
AND検索の実装が完了しています。

> テキストボックスの入力上限を定義

上記に取り掛かりたく、暫定的に上限値を考えてみました。
（以前レイアウトの調整をした際に、考慮していた気がして履歴を探したのですが見つかりませんでした…）
・ID：６桁
・名前（漢字）：小文字20、大文字、8
　※区別の概念があるのかわからないのですが一旦どちらも考慮します。
・名前（ふりがな）：10文字
・電話番号：11文字

取り急ぎ考えてみただけなので、こうした方がいいなどあれば訂正いただけましたら幸いです。
ご確認お願いいたします。

**Comment by tomohitokanno** [comment]
@ri-i-i-sa 
・ID：半角5桁
・名前（漢字）：全角10文字　半角20文字
・名前（ふりがな）：全角20文字
・電話番号：半角13文字（ハイフンを含む）

現実的なところでここらへんかなと思います。

**Comment by ri-i-i-sa** [comment]
@tomohitokanno 
度々すみません。。

色々と実装方法を調べているのですが、本タスクでの挙動は「フォーム送信前に制限がかかる（制限がかかった場合検索ができない）」が正しいでしょうか？

**Comment by tomohitokanno** [comment]
@ri-i-i-sa 
まず、当検索エリアにはformタグを使用していないため、「検索フォーム」という言葉を使用してよいかどうかわかりませんが、いったんそういう言葉の問題は置きつつ、、、
本タスクで実装する動作は、各項目に上限値以上の値を入力できなくすることです。

実現するためには以下の2つのパターンの処理を駆使する必要があります。

パターン１
電話番号を入力した場合、最大値は13です。したがって、080-1234-5678まで入力した場合、次の数字を入力してもテキストボックスに入力されないようにすることを目指してください。以下のサイトの検索項目で言うところの「出版／発行年月」と同じ動作です。
https://www.library.pref.chiba.lg.jp/licsxp-iopac/WOpacMnuTopInitAction.do


パターン２
名前（漢字）の入力最大値は半角20ですが、テキストボックスからフォーカスアウトした際に、入力されていた文字が全角文字であった場合、超過した分のみをテキストボックスから取り除くようにしてください。
例えば、入力時に「あいうえおかきくけこか」と入力した場合、テキストボックスからフォーカスアウトすると、「あいうえおかきくけこ」になるようにしてください。
テキストボックスからのフォーカスアウトはJavaScriptでイベントを検知し、文字の長さは、文字のバイト数で半角/全角文字かどうかを判定できます（他にも色々な判定方法があると思いますが）。

**Comment by tomohitokanno** [comment]
@ri-i-i-sa 
[該当コミット](https://github.com/ri-i-i-sa/member-management-system-project/pull/23/commits/6b48dbd0bef0fe888bdf50acf593f9ecba119efd)見ました。
パターン１の方はできています。
ですが全角１０以上の文字の入力ができてしまうので。パターン２の対応が必要です。
対応お願いします。

**Comment by ri-i-i-sa** [comment]
@tomohitokanno 
「条件クリア」ボタンを実装し、押下時に入力欄に文字列があった場合、空文字（"")を置き換えるを実装したいのですが、既存の入力文字を削除する方法がわからず、苦戦しています。

仮にリセットしたい対象が searchIdの場合、ボタンクリックイベント後、

 let searchId = $(".search-id").val();

パターン1
 searchId = '';

パターン2
 searchId = searchId.replace( searchId, "");

どちらも値自体は空になるのですが、表示が残ったままになります。
恐らく私のやり方が間違っているのだと思いますが、ご助言いただけましたら幸いです。

**Comment by tomohitokanno** [comment]
@ri-i-i-sa 
`let searchId = $(".search-id").val();`

はHTML上で入力した文字を変数に格納しているだけです。
ですのでその変数に対して
パターン1のように
`searchId = '';`
しても取得元である$(".search-id")へは何も変化が起きません。
`$(".search-id")`に対してなにかを代入したいのであれば、左辺を`$(".search-id")`にして代入をする必要があります。

それと以後はコーディング方法のQAや議論はpull requestへ
仕様の確認はissueへと使い分けるようにお願いします。

**Comment by ri-i-i-sa** [comment]
マージ済のためクローズ

【作業時間】
23h
