### ISSUE TITLE
特定の会員idの履歴を表示する

### ISSUE THREAD

**Issue by ri-i-i-sa** [ri-i-i-sa/member-management-system-project#8]
会員の行のボタン【来店履歴】から、特定の会員idの履歴を表示するように実装する。

spreadsheetのAPIを実装（来店テーブルに対するselect）
idを1に固定し、APIを叩いてレスポンスのjsonをconsole.logに表示できるかを確認
レスポンスのjsonを整形し、来店履歴のページの体裁を整える
idを行に埋め込んだ値を使用し、APIを叩く
検索結果0件の場合の考慮（来店履歴はありません　などのテキスト表示で良さそう）

**Comment by ri-i-i-sa** [comment]
@tomohitokanno 
レイアウト実装時に今回は実装しないとしていた下記項目について、idとおなじようにURLにパラメータを付与すれば表示自体は出来そうな気がしてきたのですが、セキュリティ上あまり望ましくないでしょうか？？？

> 2.名前
> 　→名前は来店テーブルではなくメンバーテーブルで管理しているためDBからの取得がやや混雑になります。
> 　また、画面遷移？もしくは画面別タブ表示？（ここも検討）する際に名前を受け渡すためにやや大変な未来が見えますので、マストでなければない方が良いです。

マストな実装ではないのですが、個人的にはやはり名前があった方が利便性が高いと感じた＆セキュリティ上問題なければ実装に手間がかからなそうなので一度ご相談です。

**Comment by tomohitokanno** [comment]
@ri-i-i-sa 
> レイアウト実装時に今回は実装しないとしていた下記項目について、idとおなじようにURLにパラメータを付与すれば表示自体は出来そうな気がしてきたのですが、セキュリティ上あまり望ましくないでしょうか？？？

このシステムにおいてはセキュリティ上は問題ないです。そもそも期間的な猶予がないため認証周りを一切考慮していない設計のため、セキュリティは考慮から外してください。

ですがURLパラメータに名前を見える状態で受け渡すというのはセキュリティ云々を除外してもクレイジーなので、
実装するのであればidのパラメーターから会員テーブルを検索してください。
そのためにAPIを1本増やすのか、すでにあるAPIのレスポンスのjsonに会員の名前を混ぜ込むかは自由です。

**Comment by tomohitokanno** [comment]
@ri-i-i-sa 
これとかどうでしょうか。
クエリには足すものの、名前を平文で送るのではなく、暗号化して渡し、受け取る際に復号化すれば簡易に実装できそうです。
https://www.sejuku.net/blog/52234

**Comment by ri-i-i-sa** [comment]
@tomohitokanno 
ありがとうございます！
こんな感じの手法を探していました！

ちょっと試してみます。

**Comment by ri-i-i-sa** [comment]
@tomohitokanno 
暗号化を使って、URLに名前のパラメータを受け渡し、表示させる事が出来ました。
明日コードを整形し、レビュー依頼を出させていただきます！

**Comment by ri-i-i-sa** [comment]
マージ済のためクローズ

【作業時間】
19h

**Comment by ri-i-i-sa** [comment]
マージ済のためクローズ

【作業時間】
19h
